{% set name = "msumastro" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07c1339cec12ee8545964ef24a62bfacf8183cb79fe9798eef6355a40bd3134a

build:
  noarch: python
  number: 0
  entry_points:
    - quick_add_keys_to_file.py = msumastro.scripts.quick_add_keys_to_file:main
    - run_patch.py = msumastro.scripts.run_patch:main
    - run_astrometry.py = msumastro.scripts.run_astrometry:main
    - run_triage.py = msumastro.scripts.run_triage:main
    - run_standard_header_process.py = msumastro.scripts.run_standard_header_process:main
    - sort_files.py = msumastro.scripts.sort_files:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - astropy >=3.2.2
    - numpy
    - ccdproc >=1.2

test:
  imports:
    - msumastro
    - msumastro.header_processing
  commands:
    - quick_add_keys_to_file.py --help
    - run_patch.py --help
    - run_astrometry.py --help
    - run_triage.py --help
    - run_standard_header_process.py --help
    - sort_files.py --help

about:
  home: http://github.com/mwcraig/msumastro
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Tools for doing preliminary processing of images from Feder Observatory.
  description: |
    The MSUM astro library contains scripts for add metada and astrometry to images from
    the Paul P. Feder Observatory.
  doc_url: https://msum-astro.readthedocs.io
  dev_url: https://github.com/mwcraig/msumastro

extra:
  recipe-maintainers:
    - mwcraig
