{% set name = "msumastro" %}
{% set version = "0.9.13" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "be652c92c4ee29c7ba1bac43f3a0c8c750156ca5ca6d31a2c944974892e2afbc" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  entry_points:
    - quick_add_keys_to_file.py = msumastro.scripts.quick_add_keys_to_file:main
    - run_patch.py = msumastro.scripts.run_patch:main
    - run_astrometry.py = msumastro.scripts.run_astrometry:main
    - run_triage.py = msumastro.scripts.run_triage:main
    - run_standard_header_process.py = msumastro.scripts.run_standard_header_process:main
    - sort_files.py = msumastro.scripts.sort_files:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - astropy >=2
    - numpy
    - ccdproc >=1.2

test:
  imports:
    - msumastro
    - msumastro.header_processing
  commands:
    - quick_add_keys_to_file.py --help
    - run_patch.py --help
    - run_astrometry.py --help
    - run_triage.py --help
    - run_standard_header_process.py --help
    - sort_files.py --help

about:
  home: http://github.com/mwcraig/msumastro
  license: 3-clause
  license_family: BSD
  license_file: 'LICENSE.rst'
  summary: Tools for doing preliminary processing of images from Feder Observatory.
  description: |
    The MSUM astro library contains scripts for add metada and astrometry to images from
    the Paul P. Feder Observatory.
  doc_url: https://msum-astro.readthedocs.io
  dev_url: https://github.com/mwcraig/msumastro

extra:
  recipe-maintainers:
    - mwcraig
