travis:
  secure:
    BINSTAR_TOKEN: z5LNFNfTdtDOLAnMLde3jw1OKzzsZ8QlRjbygXzPh3LnrDXIU6XeLzXpRA9VtmI9vkO6dCdiycESv1M1PesGjseZ1C2oszQtJBU0hjrfYkVR4h+R+gB6mja2hlQocJ0HjCkkdhAQXAivevJhlfZUt/Rq/FlaYPccYYYrIxNeSrnI8vXMBaSZxjpQWz3XKBkGmx0amfVOpwA8GY1n+isbZ3RYz7BDp7/09wSphEbOF2wfEq1ByzF89Cvwo+J0iWIMLs3Wd8ybqzJhiOqMchZ7M1kKI/sEAasTRQ/YgLrwCNOdHZDpxJVof4o81Av72xHFf1KjUVEGEYQa7dlHkJFCe+j6i9ENkfekdOdHKOZDTWiXmSeDbYPTsM5HKYYBwHDdgbSqylwCl/rD15vLww8bKgpX6+SJ23PvBx24BOYL5vAX2cR3ENLcnMo6ZIeobnBNYmY85QiOkmSZCjvcpqPmL1JFN4nMyFlJMXdo70ThFuhv83I//c8znhIwB1hbjW7Jrt1gJAVRIvJi0gI/zWL7xke0RXH1GUesS2CsM2gmViYulGyulThIIQO8a6lvlyXtbDrv5JzqDcis9xxmy5mwE39zQIFKRFMnoH2Xucc8re5OL6HL/xLqOkzGs11f6bA2uYkIJ0s0aKxNTAKkLs+IvY/SZzlpav+jlZXncu14C3k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
