travis:
  secure:
    BINSTAR_TOKEN: tcT5WS+bft3cmvjIUWCztHsJ0G6km8mwvyAwz2QarUFV8GyywUpnRDkXrylBAkKq7qpm5PSDLYMJXkMXDPXnvfyXZt6axHNBi74+dUc+8KDZEs9PEovvwzbClxUGd0iUCUsot9vNqwOYR5M2v9acYrJVOKBeldrz8Fenod7HKOGne7M3JJ7qc2JwEn2zL/mKphA60N8YS7xtyVxr4H5Ld2mmtoDHi6t2SMYfZi3bafrjXknNyQ+bmDvl0s3/WBaWJOMONhSfO6iHoojyQcs/ItRjXnBQjuziehYkpzHwP3cG0aNM7ufIm3OkhTBn60qNttTRRZvus5gqCGtnWMODsAWL04LLQQuVmm2AWrE5k/F3yRXrWV7JTY0jA+jzzYGzLKsnsutgufRI1tPA3EVWBzwKlDc3FF6lyHVXo0SJ0rRnkq7V9l4U886LIVa8frWXCsZSfy1IbP55XC0Itt3BHEfcefydhrARqzTNBfFSXyDkvpJwz/xufQaTWNAijOZIWHtYEDNfiUqfFa6xZOcRmqkhrtd8ugiNKTgNZliEojaojSCe/eXrlWBB8NOwCAJ6O0g6T0HnBFGvaCSeY+tYhauUB7LLLYKtqXSf8NtwmVK2tq5Ryr/YY7RBQGCQHHRYcu6WdgKXk8HnpVGUdLmcWNoPvEv7KV719bd9EQGkVJQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
