travis:
  secure:
    BINSTAR_TOKEN: ivIM4UoqbdkSJwa+xaii3jtzDlUUPTBKGs/ZphZl6t3SquEfIcaDV8cu8ownOdLCVOluWt4jvPX2po6GUCJCmfqjwbQWAtnAv+dG/j+HQfnxk9OGVeFmwwcnAXhjzsFJCiFkkbWiMQAg3V6XQ3As9+8l8xb+bt53bm/mPHb+qg1kvfc0yaBYQWrVtLMSH1wmlNyJJHhgz7wbUBVxzy16i0mTw0GiFMGVuZ7eWyrEHDcPwMDygY+T0Lad6lZSxv6A9paRUeZVTJNJij+LKFQ7aFcnm59ZEQBNFk+GSEi4we37Glyou0+JY5DkYcWFNlFMQZy7jpSFW8kgveO24JG+AQUasTcDdPGNyPP/9XKeKfiqOsD/PX4o3QMUeMVyeUCjHkFFXGM91xMl1u6NAbMzYTK3RBEYlRe/xFVToTXor1sQax7mbpihDW52I6m5RN1wHc7Sy2ctgXbrImZHNlGNT3HNtjJsyWjdoDOJ1WGBSqjDgFhfUV12LI1432OEGpZ3O2FUs2QQKtTBom5Mn6MdHJFtlaCYIiiP3iy+ebbcXbMoR1xgGVxFPUdtaCN3leeUKHK/LdiQlw0G3I2B40mC7Y1ziPbBJQS9FRBael2OZtYo4pShAoXv1i1IMTihv1kr6511np/0xvhPfYUElS5BHzWSbpRxDiia8pM4L5IrDIY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
